name: "Check Dependabot Alerts for Compliance"
description: "Check how many open Dependabot alerts are present on the current repository."
author: "Craig Bath"
branding:
  icon: "alert-circle"
  color: "purple"
inputs:
  github_personal_token:
    description: "GitHub Personal Access Token"
  compliance:
    description: "Compliance document"
outputs:
  total_alerts:
    description: "Total Open Alerts"
  critical_alerts:
    description: "Open Critical Alerts"
  high_alerts:
    description: "Open High Alertss"
  moderate_alerts:
    description: "Open Moderate Alerts"
  low_alerts:
    description: "Open Lower Alerts"
runs:
  using: "docker"
  image: "Dockerfile"
